sudo: false
language: node_js
node_js:
  - '12'

script:
  - npm audit
  - npm test

deploy:
  provider: script
  script: sls deploy
  skip_cleanup: true
  on:
    repo: tanx/photon-keyserver
    branch: master
